server:
    port: 8082
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: myClientId
      #the client Secret must not be published publicly or provided to an untrusted source
      clientSecret: secret
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      scope: user_info
    resource:
      userInfoUri: http://localhost:8081/resource/user
spring:
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security: DEBUG